"""initial schema

Revision ID: 2297bb7d26f9
Revises: 
Create Date: 2026-09-08 21:30:25.770745
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '2297bb7d26f9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_heartbeat', 'workers', [sa.literal_column('last_heartbeat_at DESC')], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_workflows_version_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_workflows_name_version')
    )
    op.create_index('ix_workflows_name_version_desc', 'workflows', ['name', sa.literal_column('version DESC')], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('executor', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.CheckConstraint('length(key) > 0', name='ck_tasks_key_not_blank'),
    sa.CheckConstraint('timeout_seconds > 0', name='ck_tasks_timeout_positive'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'key', name='uq_tasks_workflow_key')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('trigger_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NOT NULL', name='ck_runs_finished_implies_started'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_state_created', 'workflow_runs', ['state', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_runs_workflow_created', 'workflow_runs', ['workflow_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task_dependencies',
    sa.Column('parent_task_id', sa.UUID(), nullable=False),
    sa.Column('child_task_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('parent_task_id <> child_task_id', name='ck_task_deps_no_self_loop'),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_task_id', 'child_task_id')
    )
    op.create_index('ix_task_deps_child', 'task_dependencies', ['child_task_id'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('pending_deps', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(state = 'RUNNING') = (lease_expires_at IS NOT NULL AND worker_id IS NOT NULL)", name='ck_task_runs_lease_iff_running'),
    sa.CheckConstraint('attempt <= max_attempts', name='ck_task_runs_attempt_within_budget'),
    sa.CheckConstraint('attempt >= 0', name='ck_task_runs_attempt_non_negative'),
    sa.CheckConstraint('pending_deps >= 0', name='ck_task_runs_pending_deps_non_negative'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'task_id', name='uq_task_runs_run_task')
    )
    op.create_index('ix_task_runs_claimable', 'task_runs', [sa.literal_column('priority DESC'), 'scheduled_at'], unique=False, postgresql_where=sa.text("state = 'READY'"))
    op.create_index('ix_task_runs_expired_leases', 'task_runs', ['lease_expires_at'], unique=False, postgresql_where=sa.text("state = 'RUNNING'"))
    op.create_index('ix_task_runs_run_state', 'task_runs', ['run_id', 'state'], unique=False)
    op.create_table('task_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint('attempt >= 1', name='ck_task_attempts_attempt_positive'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_run_id', 'attempt', name='uq_task_attempts_run_attempt')
    )
    op.create_index('ix_task_attempts_started', 'task_attempts', [sa.literal_column('started_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_attempts_started', table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index('ix_task_runs_run_state', table_name='task_runs')
    op.drop_index('ix_task_runs_expired_leases', table_name='task_runs', postgresql_where=sa.text("state = 'RUNNING'"))
    op.drop_index('ix_task_runs_claimable', table_name='task_runs', postgresql_where=sa.text("state = 'READY'"))
    op.drop_table('task_runs')
    op.drop_index('ix_task_deps_child', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_runs_workflow_created', table_name='workflow_runs')
    op.drop_index('ix_runs_state_created', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('tasks')
    op.drop_index('ix_workflows_name_version_desc', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_workers_heartbeat', table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
